### ISSUE TITLE
M17Hosts.txt correct

### ISSUE THREAD

**Issue by sp2ong** [g4klx/M17Gateway#1]
Hi

Please correct in M17Hosts.txt

M17-ARG	m17.hblink.network	17000

to

M17-POL       m17.hblink.network	17000

m17.hblink.network is M17-POL reflector: https://m17.hblink.network/index.php

73 Waldek

**Comment by g4klx** [comment]
Will do. Thanks for spotting it. The gateway is nowhere near ready yet so no damage done.


Sent from Yahoo Mail for iPhone


On Sunday, November 1, 2020, 19:04, Waldek <notifications@github.com> wrote:




Hi

Please correct in M17Hosts.txt

M17-POL Poland

M17-ARG m17.hblink.network 17000

to

M17-POL Poland

M17-POL m17.hblink.network 17000

73 Waldek
