### ISSUE TITLE
M17Gateway testing

### ISSUE THREAD

**Issue by nostar** [g4klx/M17Gateway#3]
I flashed the M17 branch of MMDVM_HS into a hat and built M17 branch of MMDVMHost  and M17Gateway.  I needed to make these changes to get M17Gateway to pass reflector traffic to MMDVMHost:

```
diff --git a/M17Gateway.cpp b/M17Gateway.cpp
index 7ec720c..d6d4333 100644
--- a/M17Gateway.cpp
+++ b/M17Gateway.cpp
@@ -240,6 +240,8 @@ void CM17Gateway::run()
                }
        }
 
+       remoteNetwork.enable(true);
+       
        for (;;) {
                unsigned char buffer[100U];
 
diff --git a/RptNetwork.cpp b/RptNetwork.cpp
index 5cd983f..a2a949b 100644
--- a/RptNetwork.cpp
+++ b/RptNetwork.cpp
@@ -68,7 +68,7 @@ bool CRptNetwork::open()
 
 bool CRptNetwork::write(const unsigned char* data)
 {
-       if (m_addrLen != 0U)
+       if (m_addrLen == 0U)
                return false;
 
        assert(data != NULL);
```

**Comment by g4klx** [comment]
Thank you for that. I've now added it to the M17 Gateway in master. I appreciate the feedback.
    On Sunday, 8 November 2020, 07:13:33 GMT, nostar <notifications@github.com> wrote:  
 
 


I flashed the M17 branch of MMDVM_HS into a hat and built M17 branch of MMDVMHost and M17Gateway. I needed to make these changes to get M17Gateway to pass reflector traffic to MMDVMHost:
diff --git a/M17Gateway.cpp b/M17Gateway.cpp
index 7ec720c..d6d4333 100644
--- a/M17Gateway.cpp
+++ b/M17Gateway.cpp
@@ -240,6 +240,8 @@ void CM17Gateway::run()
                }
        }
 
+       remoteNetwork.enable(true);
+       
        for (;;) {
                unsigned char buffer[100U];
 
diff --git a/RptNetwork.cpp b/RptNetwork.cpp
index 5cd983f..a2a949b 100644
--- a/RptNetwork.cpp
+++ b/RptNetwork.cpp
@@ -68,7 +68,7 @@ bool CRptNetwork::open()
 
 bool CRptNetwork::write(const unsigned char* data)
 {
-       if (m_addrLen != 0U)
+       if (m_addrLen == 0U)
                return false;
 
        assert(data != NULL);

**Comment by nostar** [comment]
I made these changes for M17Gateway to pass RF data received by MMDVMHost to the M17 reflector:
```
diff --git a/M17Gateway.cpp b/M17Gateway.cpp
index 5865a30..f8e7892 100644
--- a/M17Gateway.cpp
+++ b/M17Gateway.cpp
@@ -43,6 +43,7 @@
 #include <pwd.h>
 #endif
 
+
 #if defined(_WIN32) || defined(_WIN64)
 const char* DEFAULT_INI_FILE = "M17Gateway.ini";
 #else
@@ -239,6 +240,7 @@ void CM17Gateway::run()
                }
        }
 
+       localNetwork->enable(true);
        remoteNetwork.enable(true);
 
        for (;;) {
diff --git a/RptNetwork.cpp b/RptNetwork.cpp
index a2a949b..74ee3c6 100644
--- a/RptNetwork.cpp
+++ b/RptNetwork.cpp
@@ -109,7 +109,7 @@ void CRptNetwork::clock(unsigned int ms)
        if (::memcmp(buffer + 0U, "PING", 4U) == 0)
                return;
 
-       if (::memcmp(buffer + 0U, "Rpt ", 4U) != 0) {
+       if (::memcmp(buffer + 0U, "M17 ", 4U) != 0) {
                CUtils::dump(2U, "Rpt, received unknown packet", buffer, length);
                return;
        }
```

**Comment by g4klx** [comment]
All added and committed in master.
